apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: setel/gateway
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: INTERNAL_KEY
              valueFrom:
                secretKeyRef:
                  name: all-secret
                  key: internal-key
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: all-config-map
                  key: node-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: all-config-map
                  key: gateway-port
            - name: INTROSPECTION
              valueFrom:
                configMapKeyRef:
                  name: all-config-map
                  key: introspection
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: all-config-map
                  key: gateway-service-name
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: all-config-map
                  key: log-level
            - name: LOG_INLINE
              valueFrom:
                configMapKeyRef:
                  name: all-config-map
                  key: log-inline
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: all-config-map
                  key: order-service-url
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway
  ports:
    - name: gateway
      protocol: TCP
      port: 4000
      targetPort: 4000
