# Apply before start the deployment
apiVersion: v1
kind: Secret
metadata:
  name: all-secret
type: Opaque
data:
  internal-key: dGhpc2lzcmFuZG9ta2V5
  order-mongo-user: cm9vdA==
  order-mongo-password: c2VjcmV0LXJvb3QtcHdk
  payment-mysql-user: cm9vdA==
  payment-mysql-password: c2VjcmV0LXJvb3QtcHdk
